const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const pana49formSchema = new Schema({
  category: String,
  date: Date,
  city: String,
  area_code: String,
  aotype: String,
  range_code: String,
  ao_no: String,
  title: String,
  last_name: String,
  first_name: String,
  middle_name: String,
  name_on_card: String,
  gender: String,
  dob: Date,
  single_parent: Boolean,
  mother_last_name: String,
  mother_first_name: String,
  mother_middle_name: String,
  father_last_name: String,
  father_first_name: String,
  father_middle_name: String,
  name_on_card_parent: String,
  address_type: String,
  flat: String,
  building: String,
  street: String,
  locality: String,
  town: String,
  state: String,
  pincode: String,
  country: String,
  isd_code: String,
  mobile: String,
  email: String,
  aadhaar: String,
  income_source: String,
  identity_proof: String,
  address_proof: String,
  dob_proof: String,
  declaration: String,
  filePath: String,
  signaturePath: String,
  documentsPath: String,
  verifier_name: String,
  verification_place: String,
  verification_date: Date,
  pan_option: String,
  pan_status: String,
  uniqueNumber: { type: String, unique: true } // Add the unique number field
});

const Pana49form = mongoose.model('Pana49form', pana49formSchema);
module.exports = Pana49form;
